name: SE1
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pip>=22.3
  - hydra-core=1.2
  - pytest=7.2
  - tensorboard=2.10
  - tqdm=4.64
  - seaborn=0.12
  - wandb=0.13
  - pandas-stubs=1.5
  - scikit-learn=1.2
  - gym=0.21
  - mpi4py=3.1.4
  # for bipedal-walker:
  - box2d-py=2.3.8
  # mujoco stuff:
  - gcc
  - glew
  - xorg-libx11
  - patchelf
  # C++ dependency for libfolding, for modality analysis:
  - armadillo
  # other stuff:
# NOTE: I couldn't find opengl libraries in conda-forge. Workaround is to softlink them from the global installation:
# cd path/to/conda/environments/ma-kwie/include/GL
# ln -s /usr/include/GL/gl.h .